Categories:
    - Connectivity
    - Development
    - Navigation
    - Security
    - System
License: GPL-3.0-only
AuthorName: mwarevn
SourceCode: https://github.com/minhdevs/android-gps-moving-simulation
IssueTracker: https://github.com/minhdevs/android-gps-moving-simulation/issues
Changelog: https://github.com/minhdevs/android-gps-moving-simulation/releases
Donate: https://mwarevn.github.io/donate/

AutoName: GPS Setter

RepoType: git
Repo: https://github.com/minhdevs/android-gps-moving-simulation.git
Binaries: https://github.com/minhdevs/android-gps-moving-simulation/releases/download/v%v/app-foss-arm64-v8a-release.apk

Builds:
    - versionName: 0.0.6
      versionCode: 6
      commit: v0.0.6
      subdir: app
      gradle:
          - foss

AllowedAPKSigningKeys: 64ca1fa39ddf9e0e89c57d73fb681d2a5b35ae20f071771e2eb401b5032ef1a9

MaintainerNotes: scanner detects 'com/google/android/gms/...' from 'org.microg.gms:play-services-location`

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.0.6
CurrentVersionCode: 6
